package dk.kb.cop3.backend.migrate.hibernate;
// Generated Apr 27, 2011 3:35:37 PM by Hibernate Tools 3.3.0.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class CategoryOracle implements java.io.Serializable {


     private String id;
     private String categoryText;
     private Set objects = new HashSet(0);

    public CategoryOracle() {
    }

	
    public CategoryOracle(String id, String categoryText) {
        this.id = id;
        this.categoryText = categoryText;
    }
    public CategoryOracle(String id, String categoryText, Set objects) {
       this.id = id;
       this.categoryText = categoryText;
       this.objects = objects;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCategoryText() {
        return this.categoryText;
    }
    
    public void setCategoryText(String categoryText) {
        this.categoryText = categoryText;
    }
    public Set getObjects() {
        return this.objects;
    }
    
    public void setObjects(Set objects) {
        this.objects = objects;
    }

    @Override
    public String toString() {
        return "Category{" +
                "categoryText='" + categoryText + '\'' +
                ", id='" + id + '\'' +
                '}';
    }
}


