package dk.kb.cop3.backend.migrate.hibernate;
// Generated Apr 27, 2011 3:35:37 PM by Hibernate Tools 3.3.0.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Edition generated by hbm2java
 */
public class EditionOracle implements java.io.Serializable {


     private String id;
     private String name;
     private String nameEn;
     private String urlName;
     private String urlMatrialType;
     private BigDecimal urlPubYear;
     private String urlPubMonth;
     private String urlCollection;
     private String cumulusCatalog;
     private String cumulusTopCatagory;
     private String normalisationrule;
     private String status;
     private String uiLanguage;
     private String uiSort;
     private String uiShow;
     private String opml;
     private String description;
     private String descriptionEn;
     private String collectionDa;
     private String collectionEn;
     private String departmentDa;
     private String departmentEn;
     private String contactEmail;
     private String lastModified;
     private char visiblePublic;
     private String log;


     private Set objects = new HashSet(0);

    public EditionOracle() {
    }

	
    public EditionOracle(String id, String name, String urlName, String urlMatrialType, BigDecimal urlPubYear, String urlPubMonth, String urlCollection, String cumulusCatalog, String cumulusTopCatagory, String normalisationrule) {
        this.id = id;
        this.name = name;
        this.urlName = urlName;
        this.urlMatrialType = urlMatrialType;
        this.urlPubYear = urlPubYear;
        this.urlPubMonth = urlPubMonth;
        this.urlCollection = urlCollection;
        this.cumulusCatalog = cumulusCatalog;
        this.cumulusTopCatagory = cumulusTopCatagory;
        this.normalisationrule = normalisationrule;
    }
    public EditionOracle(String id, String name, String urlName, String urlMatrialType, BigDecimal urlPubYear, String urlPubMonth, String urlCollection, String cumulusCatalog, String cumulusTopCatagory, String normalisationrule, String status, String uiLanguage, String uiSort, String uiShow, String opml, String description, String collectionDa, String collectionEn, String departmentDa, String departmentEn, String contactEmail, Set objects, char visiblePublic) {
       this.id = id;
       this.name = name;
       this.urlName = urlName;
       this.urlMatrialType = urlMatrialType;
       this.urlPubYear = urlPubYear;
       this.urlPubMonth = urlPubMonth;
       this.urlCollection = urlCollection;
       this.cumulusCatalog = cumulusCatalog;
       this.cumulusTopCatagory = cumulusTopCatagory;
       this.normalisationrule = normalisationrule;
       this.status = status;
       this.uiLanguage = uiLanguage;
       this.uiSort = uiSort;
       this.uiShow = uiShow;
       this.opml = opml;
       this.description = description;
       this.collectionDa = collectionDa;
       this.collectionEn = collectionEn;
       this.departmentDa = departmentDa;
       this.departmentEn = departmentEn;
       this.contactEmail = contactEmail;
       this.objects = objects;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrlName() {
        return this.urlName;
    }
    
    public void setUrlName(String urlName) {
        this.urlName = urlName;
    }
    public String getUrlMatrialType() {
        return this.urlMatrialType;
    }
    
    public void setUrlMatrialType(String urlMatrialType) {
        this.urlMatrialType = urlMatrialType;
    }
    public BigDecimal getUrlPubYear() {
        return this.urlPubYear;
    }
    
    public void setUrlPubYear(BigDecimal urlPubYear) {
        this.urlPubYear = urlPubYear;
    }
    public String getUrlPubMonth() {
        return this.urlPubMonth;
    }
    
    public void setUrlPubMonth(String urlPubMonth) {
        this.urlPubMonth = urlPubMonth;
    }
    public String getUrlCollection() {
        return this.urlCollection;
    }
    
    public void setUrlCollection(String urlCollection) {
        this.urlCollection = urlCollection;
    }
    public String getCumulusCatalog() {
        return this.cumulusCatalog;
    }
    
    public void setCumulusCatalog(String cumulusCatalog) {
        this.cumulusCatalog = cumulusCatalog;
    }
    public String getCumulusTopCatagory() {
        return this.cumulusTopCatagory;
    }
    
    public void setCumulusTopCatagory(String cumulusTopCatagory) {
        this.cumulusTopCatagory = cumulusTopCatagory;
    }
    public String getNormalisationrule() {
        return this.normalisationrule;
    }
    
    public void setNormalisationrule(String normalisationrule) {
        this.normalisationrule = normalisationrule;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getUiLanguage() {
        return this.uiLanguage;
    }
    
    public void setUiLanguage(String uiLanguage) {
        this.uiLanguage = uiLanguage;
    }
    public String getUiSort() {
        return this.uiSort;
    }
    
    public void setUiSort(String uiSort) {
        this.uiSort = uiSort;
    }
    public String getUiShow() {
        return this.uiShow;
    }
    
    public void setUiShow(String uiShow) {
        this.uiShow = uiShow;
    }
    public String getOpml() {
        return this.opml;
    }
    
    public void setOpml(String opml) {
        this.opml = opml;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCollectionDa() {
        return this.collectionDa;
    }
    
    public void setCollectionDa(String collectionDa) {
        this.collectionDa = collectionDa;
    }
    public String getCollectionEn() {
        return this.collectionEn;
    }
    
    public void setCollectionEn(String collectionEn) {
        this.collectionEn = collectionEn;
    }
    public String getDepartmentDa() {
        return this.departmentDa;
    }
    
    public void setDepartmentDa(String departmentDa) {
        this.departmentDa = departmentDa;
    }
    public String getDepartmentEn() {
        return this.departmentEn;
    }
    
    public void setDepartmentEn(String departmentEn) {
        this.departmentEn = departmentEn;
    }
    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }
    public Set getObjects() {
        return this.objects;
    }
    
    public void setObjects(Set objects) {
        this.objects = objects;
    }

    public String getLastModified() {
        return lastModified;
    }

    public void setLastModified(String lastModified) {
        this.lastModified = lastModified;
    }

    public char getVisiblePublic() {
        return visiblePublic;
    }

    public void setVisiblePublic(char visiblePublic) {
        this.visiblePublic = visiblePublic;
    }
    
    public String getLog() {
	return log;
    }

    public void setLog(String log) {
	this.log = log;
    }

    public String getNameEn() {
        return nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    public String getDescriptionEn() {
        return descriptionEn;
    }

    public void setDescriptionEn(String descriptionEn) {
        this.descriptionEn = descriptionEn;
    }

    @Override
    public String toString() {
        return "Edition{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", urlName='" + urlName + '\'' +
                ", urlMatrialType='" + urlMatrialType + '\'' +
                ", urlPubYear=" + urlPubYear +
                ", urlPubMonth='" + urlPubMonth + '\'' +
                ", urlCollection='" + urlCollection + '\'' +
                ", cumulusCatalog='" + cumulusCatalog + '\'' +
                ", cumulusTopCatagory='" + cumulusTopCatagory + '\'' +
                ", normalisationrule='" + normalisationrule + '\'' +
                ", status='" + status + '\'' +
                ", uiLanguage='" + uiLanguage + '\'' +
                ", uiSort='" + uiSort + '\'' +
                ", uiShow='" + uiShow + '\'' +
                ", opml='" + opml + '\'' +
                ", description='" + description + '\'' +
                ", collectionDa='" + collectionDa + '\'' +
                ", collectionEn='" + collectionEn + '\'' +
                ", departmentDa='" + departmentDa + '\'' +
                ", departmentEn='" + departmentEn + '\'' +
                ", contactEmail='" + contactEmail + '\'' +
                ", lastModified='" + lastModified + '\'' +
                ", visiblePublic='" + visiblePublic + '\'' +
           //     ", objects=" + objects +
                '}';
    }

    public String prettyPrint(){
        return  cumulusCatalog + "[" + cumulusTopCatagory + "] : /" + urlMatrialType + "/" + urlCollection + "/" + urlPubYear + "/" + urlPubMonth + "/" + urlName + "/";
    }


}


