package dk.kb.cop3.backend.migrate.hibernate;
// Generated Apr 27, 2011 3:35:37 PM by Hibernate Tools 3.3.0.GA



import dk.kb.cop3.backend.crud.database.type.JGeometryType;
import oracle.spatial.geometry.JGeometry;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Object generated by hbm2java
 */
public class ObjectOracle implements java.io.Serializable {


     private String id;
     private TypeOracle typeOracle;
     private EditionOracle edition;
     private String mods;
     private String lastModified;
     private char deleted;
     private String lastModifiedBy;
     private BigDecimal objVersion;
     private JGeometryType point;

     private String title;
     private String creator;

     private BigInteger likes; // how many liked this
     private BigInteger bookmark;
     private BigDecimal correctness;
     private BigDecimal randomNumber;
     private BigDecimal interestingess;
     private String person;
     private String building;
     private String location;
     private Date notBefore;
     private Date notAfter;
     private Set categories = new HashSet(0);
     private Set keywords = new HashSet(0);  // tags!
     private Set comments = new HashSet(0);

    public ObjectOracle() {
            this.randomNumber= new BigDecimal(Math.random());
            this.interestingess = new BigDecimal(0);
            this.correctness = new BigDecimal(0);
            this.bookmark = new BigInteger(String.valueOf(0));
            this.likes = new BigInteger(String.valueOf(0));
    }

	
    public ObjectOracle(String id, TypeOracle typeOracle, EditionOracle edition, String mods, String lastModified, char deleted, String lastModifiedBy, BigDecimal objVersion, BigDecimal randomNumber, BigDecimal interestingess) {
        this.id = id;
        this.typeOracle = typeOracle;
        this.edition = edition;
        this.mods = mods;
        this.lastModified = lastModified;
        this.deleted = deleted;
        this.lastModifiedBy = lastModifiedBy;
        this.objVersion = objVersion;
        this.randomNumber = randomNumber;
        this.interestingess = interestingess;
    }
    public ObjectOracle(String id, TypeOracle typeOracle, EditionOracle edition, String mods, String lastModified, char deleted, String lastModifiedBy, BigDecimal objVersion, JGeometryType point, String title, String creator, BigDecimal randomNumber, BigDecimal interestingess, String person, String building, String location, Date notBefore, Date notAfter, Set categories) {
       this.id = id;
       this.typeOracle = typeOracle;
       this.edition = edition;
       this.mods = mods;
       this.lastModified = lastModified;
       this.deleted = deleted;
       this.lastModifiedBy = lastModifiedBy;
       this.objVersion = objVersion;
       this.point = point;
       this.title = title;
       this.creator = creator;
       this.randomNumber = randomNumber;
       this.interestingess = interestingess;
       this.person = person;
       this.building = building;
       this.location = location;
       this.notBefore = notBefore;
       this.notAfter = notAfter;
       this.categories = categories;
    }

    public String toString(){
        return  "id: " + this.id + "\n" +
                "type: " + this.typeOracle + "\n" +
                "edition: " + this.edition + "\n" +
                "mods: " + this.mods + "\n" +
                "lastModified: " + this.lastModified + "\n" +
                "deleted: " + this.deleted + "\n" +
                "lastModifiedBy: " + this.lastModifiedBy + "\n" +
                "objVersion: " + this.objVersion + "\n" +
                "point: " + this.point + "\n" +
                "title: " + this.title + "\n" +
                "creator: " + this.creator + "\n" +
                "randomNumber: " + this.randomNumber + "\n" +
                "interestingess: " + this.interestingess + "\n" +
                "person: " + this.person + "\n" +
                "building: " + this.building + "\n" +
                "location: " + this.location + "\n" +
                "notBefore: " + this.notBefore + "\n" +
                "notAfter: " + this.notAfter + "\n" +
                "categories: " + this.categories;


    }

    public ObjectOracle(String id, TypeOracle typeOracle, EditionOracle edition, String mods, String lastModified, char deleted, String lastModifiedBy, BigDecimal objVersion, JGeometryType point, String title, String creator, BigInteger likes, BigInteger bookmark, BigDecimal correctness, BigDecimal randomNumber, BigDecimal interestingess, String person, String building, String location, Date notBefore, Date notAfter, Set categories, Set keywords) {
        this.id = id;
        this.typeOracle = typeOracle;
        this.edition = edition;
        this.mods = mods;
        this.lastModified = lastModified;
        this.deleted = deleted;
        this.lastModifiedBy = lastModifiedBy;
        this.objVersion = objVersion;
        this.point = point;
        this.title = title;
        this.creator = creator;
        this.likes = likes;
        this.bookmark = bookmark;
        this.correctness = correctness;
        this.randomNumber = randomNumber;
        this.interestingess = interestingess;
        this.person = person;
        this.building = building;
        this.location = location;
        this.notBefore = notBefore;
        this.notAfter = notAfter;
        this.categories = categories;
        this.keywords = keywords;
    }

    public BigInteger getLikes() {
        return likes;
    }

    public void setLikes(BigInteger likes) {
        this.likes = likes;
    }

    public BigInteger getBookmark() {
        return bookmark;
    }

    public void setBookmark(BigInteger bookmark) {
        this.bookmark = bookmark;
    }

    public BigDecimal getCorrectness() {
        return correctness;
    }

    public void setCorrectness(BigDecimal correctness) {
        this.correctness = correctness;
    }

    public Set getKeywords() {
        return keywords;
    }

    public void setKeywords(Set keywords) {
        this.keywords = keywords;
    }

    public Set getComments() {
        return comments;
    }

    public void setComments(Set comments) {
        this.comments = comments;
    }

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public TypeOracle getType() {
        return this.typeOracle;
    }
    
    public void setType(TypeOracle typeOracle) {
        this.typeOracle = typeOracle;
    }
    public EditionOracle getEdition() {
        return this.edition;
    }
    
    public void setEdition(EditionOracle edition) {
        this.edition = edition;
    }
    public String getMods() {
        return this.mods;
    }
    
    public void setMods(String mods) {
        this.mods = mods;
    }
    public String getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(String lastModified) {
        this.lastModified = lastModified;
    }
    public char getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(char deleted) {
        this.deleted = deleted;
    }
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }
    
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }
    public BigDecimal getObjVersion() {
        return this.objVersion;
    }
    
    public void setObjVersion(BigDecimal objVersion) {
        this.objVersion = objVersion;
    }
    public JGeometryType getPoint() {
        return this.point;
    }
    
    public void setPoint(JGeometryType point) {
        this.point = point;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public BigDecimal getRandomNumber() {
        return this.randomNumber;
    }
    
    public void setRandomNumber(BigDecimal randomNumber) {
        this.randomNumber = randomNumber;
    }
    public BigDecimal getInterestingess() {
        return this.interestingess;
    }
    
    public void setInterestingess(BigDecimal interestingess) {
        this.interestingess = interestingess;
    }
    public String getPerson() {
        return this.person;
    }
    
    public void setPerson(String person) {
        this.person = person;
    }
    public String getBuilding() {
        return this.building;
    }
    
    public void setBuilding(String building) {
        this.building = building;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Date getNotBefore() {
        return this.notBefore;
    }
    
    public void setNotBefore(Date notBefore) {
        this.notBefore = notBefore;
    }
    public Date getNotAfter() {
        return this.notAfter;
    }
    
    public void setNotAfter(Date notAfter) {
        this.notAfter = notAfter;
    }
    public Set getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set categories) {
        this.categories = categories;
    }




}


