package dk.kb.cop3.backend.migrate.hibernate;
// Generated Apr 27, 2011 3:35:37 PM by Hibernate Tools 3.3.0.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class TypeOracle implements java.io.Serializable {


     private BigDecimal id;
     private String typeText;
     private Set objects = new HashSet(0);

    public TypeOracle() {
    }

	
    public TypeOracle(BigDecimal id, String typeText) {
        this.id = id;
        this.typeText = typeText;
    }
    public TypeOracle(BigDecimal id, String typeText, Set objects) {
       this.id = id;
       this.typeText = typeText;
       this.objects = objects;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getTypeText() {
        return this.typeText;
    }
    
    public void setTypeText(String typeText) {
        this.typeText = typeText;
    }
    public Set getObjects() {
        return this.objects;
    }
    
    public void setObjects(Set objects) {
        this.objects = objects;
    }

    @Override
    public String toString() {
        return "Type{" +
                "id=" + id +
                ", typeText='" + typeText + '\'' +
                '}';
    }
}


