package dk.kb.cop3.backend.crud.database.hibernate;
// Generated Apr 27, 2011 3:35:37 PM by Hibernate Tools 3.3.0.GA




import org.locationtech.jts.geom.Geometry;
import org.locationtech.jts.geom.GeometryCollection;

import java.math.BigDecimal;

/**
 * AuditTrail generated by hbm2java
 */
public class AuditTrail  implements java.io.Serializable {


     private String id;
     private String oid;
     private String eid;
     private String mods;
     private String lastModified;
     private char deleted;
     private String lastModifiedBy;
     private BigDecimal objVersion;
     private Geometry point;

    public AuditTrail() {
    }

	
    public AuditTrail(String id, String oid, String lastModified, char deleted, String lastModifiedBy, BigDecimal objVersion) {
        this.id = id;
        this.oid = oid;
        this.lastModified = lastModified;
        this.deleted = deleted;
        this.lastModifiedBy = lastModifiedBy;
        this.objVersion = objVersion;
    }
    public AuditTrail(String id, String oid, String eid, String mods, String lastModified, char deleted, String lastModifiedBy, BigDecimal objVersion, Geometry point) {
       this.id = id;
       this.oid = oid;
       this.eid = eid;
       this.mods = mods;
       this.lastModified = lastModified;
       this.deleted = deleted;
       this.lastModifiedBy = lastModifiedBy;
       this.objVersion = objVersion;
       this.point = point;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getOid() {
        return this.oid;
    }
    
    public void setOid(String oid) {
        this.oid = oid;
    }
    public String getEid() {
        return this.eid;
    }
    
    public void setEid(String eid) {
        this.eid = eid;
    }
    public String getMods() {
        return this.mods;
    }
    
    public void setMods(String mods) {
        this.mods = mods;
    }
    public String getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(String lastModified) {
        this.lastModified = lastModified;
    }
    public char getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(char deleted) {
        this.deleted = deleted;
    }
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }
    
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }
    public BigDecimal getObjVersion() {
        return this.objVersion;
    }
    
    public void setObjVersion(BigDecimal objVersion) {
        this.objVersion = objVersion;
    }
    public Geometry getPoint() {
        return this.point;
    }
    
    public void setPoint(GeometryCollection point) {
        this.point = point;
    }

    @Override
    public String toString() {
        return "AuditTrail{" +
                "id='" + id + '\'' +
                ", oid='" + oid + '\'' +
                ", eid='" + eid + '\'' +
                ", mods='" + mods + '\'' +
                ", lastModified='" + lastModified + '\'' +
                ", deleted=" + deleted +
                ", lastModifiedBy='" + lastModifiedBy + '\'' +
                ", objVersion=" + objVersion +
                ", point=" + point +
                '}';
    }
}


